fix: 	src/features/earn-with-us/PipelineBackground.tsx(6,29): error TS2554: Expected 1 arguments, but got 0. src/features/solution/Solution.tsx(49,35): error TS2339: Property 'text' does not exist on type 'never'. src/features/solution/Solution.tsx(50,74): error TS2339: Property 'highlight' does not exist on type 'never'.